version = 0.1

[default.global.parameters]
stack_name = "sam-eda-dev"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
parameter_overrides = "Environment=dev EmailAddress=listowel.moro@amalitech.com"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[prod.global.parameters]
stack_name = "sam-eda-prod"

[prod.deploy.parameters]
parameter_overrides = "Environment=prod EmailAddress=listowel.moro@amalitech.com"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
